version: "3.7"
services:
  webserver:    
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - ${HTTP_PORT:-80}:80
    volumes:
      - ./data/:/var/www/html
    networks:
      - php-mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'phpmysql:/var/lib/mysql'
    networks:
      - php-mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    restart: unless-stopped
networks:
    php-mysql:
      driver: bridge
volumes:
    phpmysql:
      driver: local