version: '3.3'
services:
    portainer-ce:
        environment:
            - TZ=Africa/Johannesburg
        ports:
            - '9443:9443'
            - '8000:8000'
        container_name: portainer
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'data:/data'
        image: portainer/portainer-ce
volumes:
  data: